name: Publish to NPM
# on:
#   release:
#     types: [created]
on: push

jobs:
    buld-and-deploy:
      runs-on: ubuntu-latest
      steps:
       - name: checkout to repositor
         uses: actions/checkout@v2
       - name: install and build
         run: npm ci
       - name: publish to registry
         uses: actions/setup-node@v2
         with:
           node-version: 16
           registry-url: 'https://npm.pkg.github.com'
           scope: '@alexsandrbarabash'
       - name: dsf
         uses: JS-DevTools/npm-publish@v1
         with:
           token: ${{ secrets.NPM_TOKEN }}
           registry: 'https://npm.pkg.github.com'
#        - run: npm publish
#          env:
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 12
#       - run: npm install
#       - run: npm test
#       - uses: JS-DevTools/npm-publish@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           registry: 'https://npm.pkg.github.com'
