name: Publish to NPM
on:
  release:
    types: [created]
jobs:
    buld-and-deploy:
      runs-on: ubuntu-latest
      steps:
       - name: checkout to repositor
         uses: actions/checkout@v2
       - name: install and build
         run: npm ci
       - name: publish to registry
         uses: actions/setup-node@v2
         with:
           node-version: 16
           registry-url: 'https://npm.pkg.github.com'
           scope: '@alexsandrbarabash'
       - run: npm publish
         env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}